name: Docker Image Publish

on:
  push:
    pull_request:
      branches: 
      - master
    paths:
      - ".env/**"
      - ".github/workflows/docker-publish.yml"

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_TAG: master

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Downcase env variables
        run: |
          echo "IMAGE_LOWERCASE_NAME=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
          echo "IMAGE_LOWERCASE_OWNER=${GITHUB_ACTOR@L}" >> "${GITHUB_ENV}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .env/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GITHUB_REGISTRY }}${{ env.IMAGE_LOWERCASE_NAME }}:${{ env.IMAGE_TAG }}
          cache-to: type=gha,mode=max
  
  build-apptainer-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
        contents: read
        packages: write
    container:
        image: quay.io/singularity/singularity:v4.1.0
        options: --privileged
    steps:
      - name: Downcase env variables
        shell: bash
        run: |
          echo "IMAGE_LOWERCASE_NAME=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
          echo "IMAGE_LOWERCASE_OWNER=${GITHUB_ACTOR@L}" >> "${GITHUB_ENV}"
          
      - name: Check out code for the container build
        uses: actions/checkout@v4

      - name: Build Container
        run: |
           singularity build apptainer.sif .env/apptainer.def

      - name: Login and Deploy Container
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
           singularity push apptainer.sif oras://${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_LOWERCASE_OWNER }}:${{ env.IMAGE_TAG }}

